import {rooms,roomOrder,roomFor,objectsFor,isWalkable,pathTo,W,H,T} from './world-data.js';
export function mountWorld(canvas,{phase,highest,location,onInteract,onRoom,onNearby,onMove=()=>{},blocked,amended=0,reduced=()=>false}){
 const room=location.room,layout=rooms[room],objects=objectsFor(room,phase,highest);
 let player={x:location.x??11,y:location.y??11},facing='down',last=0,frame=0,keys=new Set(),path=[],arrival=null,disposed=false,lastNear='';
 const ctx=canvas.getContext('2d');canvas.width=W*T;canvas.height=H*T;
 function nearest(){return objects.find(o=>Math.abs(o.x-player.x)+Math.abs(o.y-player.y)<=1)||null;}
 function rect(x,y,w,h,c){ctx.fillStyle=c;ctx.fillRect(Math.round(x),Math.round(y),w,h);}
 function person(x,y,c,dir='down',bill=false){const bob=reduced()?0:Math.floor(frame/24)%2;rect(x+5,y+19,15,4,'#142b3270');if(bill){rect(x+6,y+2+bob,14,19,'#ecd791');rect(x+8,y+4+bob,10,15,'#fff0b8');rect(x+17,y+2+bob,3,5,'#b8a374');rect(x+10,y+9+bob,2,2,'#263c3e');rect(x+15,y+9+bob,2,2,'#263c3e');rect(x+9,y+14+bob,7,1,'#ae985e');const stride=!reduced()&&(keys.size||path.length)?Math.floor(frame/5)%2:0;rect(x+8,y+21,4,2+stride,'#a68b58');rect(x+15,y+21,4,3-stride,'#a68b58');for(let i=0;i<Math.min(3,amended);i++)rect(x+8+i*3,y+17+bob,2,2,'#b95e4c');}else{rect(x+8,y+2,10,10,'#c7a181');rect(x+7,y+1,12,4,'#3e3432');rect(x+6,y+12,14,9,c);rect(x+8,y+21,4,3,'#202e38');rect(x+15,y+21,4,3,'#202e38');if(dir==='up')rect(x+8,y+5,10,5,'#3e3432');else rect(x+(dir==='left'?8:dir==='right'?15:10),y+7,2,2,'#303139');if(dir==='down')rect(x+15,y+7,2,2,'#303139');}}
 function draw(){
  if(disposed)return;frame++;rect(0,0,W*T,H*T,'#131f29');const [l,t,r,b]=layout.size;
  for(let y=t;y<=b;y++)for(let x=l;x<=r;x++){const wall=x===l||x===r||y<3||y===b;rect(x*T,y*T,T,T,wall?layout.walls:layout.floor);if(!wall){rect(x*T,y*T,T,1,'#c4bb8520');rect(x*T,y*T,1,T,'#10242f33');if((x*7+y*11)%9===0)rect(x*T+5,y*T+15,10,1,'#eee1b014');}else if(y===2){rect(x*T,y*T+15,T,5,'#a29c72');rect(x*T,y*T+20,T,4,'#1d2c2d');}}
  // Recessed windows, warm sconces, columns, and a carpet give the room depth.
  for(const x of (room==='corridor'?[]:[l+2,r-3])){rect(x*T,14,42,37,'#111f33');rect(x*T+3,16,36,30,'#709798');rect(x*T+20,16,3,31,'#c1b887');rect(x*T+2,31,38,3,'#c1b887');ctx.fillStyle='#b8d5bc12';ctx.beginPath();ctx.moveTo(x*T,54);ctx.lineTo(x*T+44,54);ctx.lineTo(x*T+75,170);ctx.lineTo(x*T-18,170);ctx.fill();}
  rect(10*T,3*T,4*T,11*T,'#253d4560');rect(10*T,3*T,2,11*T,'#c9b47770');rect(14*T-2,3*T,2,11*T,'#c9b47770');
  if(room==='executive'){rect(7*T,8*T,10*T,4*T,'#344d5e');rect(7*T+4,8*T+4,10*T-8,4*T-8,'#47616b');}
  for(const [x,y,kind] of layout.props){let px=x*T,py=y*T;rect(px+2,py+19,25,8,'#18283255');if(kind==='plant'){rect(px+8,py+14,12,10,'#987955');rect(px+3,py+4,21,9,'#375945');rect(px+8,py-2,12,15,'#54795b');}else if(kind==='flag'){rect(px+3,py-15,2,39,'#cab680');rect(px+5,py-13,15,20,room==='senate'?'#87719e':'#597e9a');rect(px+8,py-10,3,3,'#dcc688');}else if(kind==='shelf'){rect(px,py-13,24,36,'#473e33');for(let i=0;i<5;i++)rect(px+2+i*4,py-8,3,13,['#8c966a','#ac7956','#668b95'][i%3]);rect(px,py+7,24,3,'#aa9169');}else{rect(px+2,py+3,22,18,'#493a32');rect(px,py,24,16,kind==='chair'?'#405763':'#997b50');rect(px+1,py+1,22,3,'#c0a377');if(kind.includes('paper')){rect(px+5,py+4,13,9,kind==='house-paper'?'#9eb9c8':'#bba5ca');rect(px+7,py+7,8,1,'#5e6476');ctx.font='7px monospace';ctx.fillStyle='#fff0b8';ctx.fillText(kind==='house-paper'?'HOUSE':'SENATE',px-2,py-6);}}}
  for(const o of objects){let x=o.x*T,y=o.y*T;if(o.type==='door'){rect(x-8,y-23,40,47,'#101c28');rect(x-10,y-25,44,4,'#a69669');rect(x-8,y-21,4,45,'#887b5d');rect(x+27,y-21,4,45,'#887b5d');rect(x-4,y-20,31,43,o.locked?'#44454c':'#49787a');rect(x+19,y+6,3,3,'#ddc57f');ctx.font='6px monospace';ctx.textAlign='center';ctx.fillStyle=o.locked?'#aaa58c':'#e2d3a2';ctx.fillText((o.to==='corridor'?'CAPITOL':o.to).toUpperCase(),x+12,y-29);ctx.textAlign='left';}else if(o.type==='evidence'){rect(x,y,23,20,'#594b3b');rect(x+2,y+1,9,13,'#decea1');rect(x+12,y+1,9,13,'#bbad86');}else{const near=Math.abs(o.x-player.x)+Math.abs(o.y-player.y)<=1;person(x,y,o.color||'#c6aa67',near?(player.x<o.x?'left':player.x>o.x?'right':player.y<o.y?'up':'down'):'down');}}
  person(player.x*T,player.y*T,'',facing,true);
  const near=nearest();for(const o of objects){if((o.id==='main'&&room===roomFor(phase))||(o.type==='door'&&(room==='corridor'?o.to===roomFor(phase):room!==roomFor(phase)&&o.to==='corridor'))||o===near){const x=o.x*T+10,y=o.y*T-12;rect(x-5,y-7,12,11,o===near?'#efda99':'#d9b66b');ctx.font='bold 10px monospace';ctx.fillStyle='#24323b';ctx.fillText(o===near?'E':'!',x-2,y+2);}}
  ctx.fillStyle='#10222e44';ctx.fillRect(0,0,W*T,7);rect(0,H*T-5,W*T,5,'#0c1826');
  if(near?.id!==lastNear){lastNear=near?.id;onNearby(near,player);}location.x=player.x;location.y=player.y;
 }
 function interact(o=nearest()){if(blocked())return;if(!o){onNearby(null,player);return;}if(o.type==='door'){if(o.locked){onInteract({name:'Door notice',beats:['Your bill has not reached this room yet. Check the note above the map for your next stop.']});return;}onRoom(o.to);return;}onInteract(o);}
 function step(dx,dy){facing=dx<0?'left':dx>0?'right':dy<0?'up':'down';if(isWalkable(room,player.x+dx,player.y+dy,objects)){player.x+=dx;player.y+=dy;onMove({...player});}draw();}
 function keydown(e){if(blocked()||e.target!==canvas)return;const key=e.key.toLowerCase();if(['arrowup','arrowdown','arrowleft','arrowright','w','a','s','d','e','enter',' '].includes(key)){e.preventDefault();if(['e','enter',' '].includes(key)){if(!e.repeat)interact();}else{keys.add(key);path=[];arrival=null;if(!e.repeat){const [dx,dy]=({arrowup:[0,-1],w:[0,-1],arrowdown:[0,1],s:[0,1],arrowleft:[-1,0],a:[-1,0],arrowright:[1,0],d:[1,0]})[key];step(dx,dy);last=performance.now();}}}}
 function keyup(e){keys.delete(e.key.toLowerCase());}function clear(){keys.clear();}
 function go(o){canvas.focus();if(blocked())return;keys.clear();if(Math.abs(o.x-player.x)+Math.abs(o.y-player.y)<=1){interact(o);return;}path=pathTo(room,player,o,objects);arrival=o;}
 function click(e){const b=canvas.getBoundingClientRect(),x=Math.floor((e.clientX-b.left)/b.width*W),y=Math.floor((e.clientY-b.top)/b.height*H);const o=objects.find(o=>o.x===x&&Math.abs(o.y-y)<=1);if(o)return go(o);canvas.focus();keys.clear();arrival=null;path=pathTo(room,player,{x,y},objects);const end=path.at(-1)||player;if(isWalkable(room,x,y,objects)&&Math.abs(end.x-x)+Math.abs(end.y-y)===1)path.push({x,y});}
 function loop(time){if(disposed)return;if(!blocked()&&time-last>115){last=time;if(path.length){player=path.shift();onMove({...player});if(!path.length&&arrival){const o=arrival;arrival=null;interact(o);}}else if(keys.size){if(keys.has('arrowup')||keys.has('w'))step(0,-1);else if(keys.has('arrowdown')||keys.has('s'))step(0,1);else if(keys.has('arrowleft')||keys.has('a'))step(-1,0);else if(keys.has('arrowright')||keys.has('d'))step(1,0);}}else if(blocked()){keys.clear();path=[];arrival=null;}draw();requestAnimationFrame(loop);}
 document.addEventListener('keydown',keydown);document.addEventListener('keyup',keyup);window.addEventListener('blur',clear);canvas.addEventListener('click',click);requestAnimationFrame(loop);
 return {go,objects,interact,dispose(){disposed=true;document.removeEventListener('keydown',keydown);document.removeEventListener('keyup',keyup);window.removeEventListener('blur',clear);canvas.removeEventListener('click',click);}};
}
